FROM liuboss/pami:liucb-py36-cuda10-torch151
LABEL version="1.0"
EXPOSE 8080
RUN apt-get update
RUN apt-get install  libsm6 libxrender1 libxext-dev gcc -y
RUN cd /tmp && wget https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh && sh -c '/bin/echo -e "\nyes\n\nyes" | sh Anaconda3-2019.03-Linux-x86_64.sh' && rm Anaconda3-2019.03-Linux-x86_64.sh
RUN echo -e "\ny" | /root/anaconda3/bin/conda install python=3.6
RUN /root/anaconda3/bin/pip install easydict opencv-contrib-python==4.0.0.21 Cython h5py pandas requests bs4 matplotlib lxml -U pillow keras==2.2.4 tensorflow==1.13.1 -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN pip install torch==1.6.0 && pip install torchvision==0.7.0
#RUN echo -e "\ny" | /root/anaconda3/bin/conda install pytorch-cpu torchvision-cpu -c pytorch
#RUN cd /chineseocr/text/detector/utils && sh make-for-cpu.sh
#RUN conda clean -p
#RUN conda clean -t
